<?php
/**
 * @file slider.module
 * 
 * Displays a JavaScript powered slider block w/ customizable slides
 */

/**
 * Implements hook_block_info()
 */
function slider_block_info() {
	$blocks['slider'] = array(
		'info' => t('Slider w/ customizable slides'),
		'status' => TRUE,
		'region' => 'footer',
		'weight' => 1,
		'visibility' => 1,
	);
	return $blocks;
}

/**
 * Slider module initialization
 * Implements hook_init()
 */
function slider_init() {
	// Load AnythingSlider jQuery library, dependencies, and base CSS
	if (module_exists('libraries')) {
		$slider_lib = libraries_get_path('anythingslider');
		$js_libs = array(
			$slider_lib . '/js/jquery.easing.1.2.js',
			$slider_lib . '/js/swfobject.js',
			$slider_lib . '/js/jquery.anythingslider.js',
			$slider_lib . '/js/jquery.anythingslider.video.js',
		);
		$css_files = array(
			$slider_lib . '/css/anythingslider.css',
			$slider_lib . '/css/theme-metallic.css',
		);
		$custom_js = <<<END_JS
(function($){
	$(document).ready(function() {
		$('#slider').anythingSlider({
			theme: 'metallic',
			easing: 'easeInQuad',
			onSlideComplete: function(slider) {
				console.log('slide transition');
			}
		});
	});
})(jQuery);
END_JS;
		foreach ($js_libs as $lib) {
			drupal_add_js($lib, 'file');
		}
		drupal_add_js($custom_js, 'inline');
		foreach ($css_files as $css) {
			drupal_add_css($css, 'file');
		}
		pretty_r('Init complete');
	}
}

/**
 * Implements hook_menu()
 */
function slider_menu() {
	$items['admin/config/slider'] = array(
		'title' => 'Slider',
		'description' => 'JS Slider w/ customizable slides',
		'position' => 'right',
		'weight' => -5,
		'page callback' => 'system_admin_menu_block_page',
		'access arguments' => array('administer site configuration'),
		'file' => 'system.admin.inc',
		'file path' => drupal_get_path('module', 'system'),
	);

	$items['admin/config/slider/settings'] = array(
		'title' => 'Slider Block Settings',
		'description' => 'Slider Widget Settings',
		'page arguments' => array('slider_admin_settings'),
		'access arguments' => array('administer site configuration'),
		'type' => MENU_NORMAL_ITEM,
		'file' => 'slider.admin.inc',
	);

	return $items;
}

/**
 * Implements hook_theme()
 */
function slider_theme() {
	return array(
		'slider_block_item' => array(
			'variables' => array('item' => NULL),
		),
		'slider_block_widget' => array(
			'variables' => array('items' => NULL),
		),
	);
}

/**
 * THEME HELPER FUNCTIONS
 */
function theme_slider_block_item($item) {
	$output = "<div class='slider-item'>\n";
	$output .= "</div>";
	return $output;
}

function theme_slider_block_widget($items) {
	$output = "<div id='liuna-slider'>\n";
	foreach ($items['items'] as $slide) {
		$output .= theme('slider_block_item', array('item' => $slide));
	}

	$output .= "</div>\n";
	return $output;
}

/**
 * Implements hook_block_view()
 */
function slider_block_view($delta = '') {
	switch ($delta) {
		case 'slider':
			$block['subject'] = t('Slider');
			$block['content'] = slider_block_contents($delta);
			pretty_r($block['content']);
			return $block;
			break;
	}
}

/**
 * Provides content for block_view function above
 */
function slider_block_contents($delta) {
	// hard-coded slider items for development
	$slides = array(
		array(
			'title' => 'Outer Space',
			'caption' => 'Lorem ipsum dollar',
			'src' => 'http://flickholdr.com/900/290/astronomy',
		),
		array(
			'title' => 'Inner Space',
			'caption' => 'Journey to the center of the mind',
			'src' => 'http://flickholdr.com/900/290/mind',
		),
		array(
			'title' => 'Landscape',
			'caption' => 'Landscapes are pretty',
			'src' => 'http://flickholdr.com/900/290/landscape'
		),
	);
	$slider_html = theme('slider_block_widget', array('items' => $slides));
	return array('#markup' => $slider_html);
}

// vim: set ft=php :
?>
