<?php

function union_node_info(){
	return array(
		'union'=> array(
			'name' 		=> 'Union Pages',
			'base' 		=> 'union',
			'description'	=> 'site About pages',
			'has_title'	=> 'TRUE',
			'title_label'	=> 'Page Name',
			'help'		=> 'Page will be displayed in menu under the FAQ page'
		)
	);
};


function union_block_info(){
	$items=array();
		$items['union_info'] = array();
		$items['union_info']['info'] = 'Union Info';

			return $items;
}

function union_theme(){

	$items = array();
		$items['union_info'] = array();
		$items['union_info']['variables']	= array('node'=>NULL,'info'=>NULL);
		$items['union_info']['file']		= 'union.block.inc';
		$items['union_info']['template']	= 'union-info';
			return $items;
}

function union_block_view($delta){
	$block = array();

	switch ($delta){
	case 'union_info':
		global $union_nid;
		if(!isset($union_nid)){
			return;
		}
			$block['subject'] = NULL;
			$block['content'] = union_info_block_contents($delta);
		
		break;
	}

	return $block;
}



function union_info_block_contents($delta){
	global $union_nid;
	$content = theme('union_info',array('node'=> node_load($union_nid)));
	return $content;
}


/**
 * Implement hook_form() with the standard default form.
 */
function union_form($node,$form_state){
	xdebug_break();
	return node_content_form($node,$form_state);
}

function union_node_access($node, $op, $account) {
 
	$type = is_string($node) ? $node : $node->type;

	$q=user_access('create ' . $type . ' content', $account);
	$qq=user_role_permissions(array('admin'));
	$qqq='create ' . $type . ' content';

  if (in_array($type, node_permissions_get_configured_types())) {
    if ($op == 'create' && user_access('create ' . $type . ' content', $account)) {
      return NODE_ACCESS_ALLOW;
    }

    if ($op == 'update') {
      if (user_access('edit any ' . $type . ' content', $account) || (user_access('edit own ' . $type . ' content', $account) && ($account->uid == $node->uid))) {
        return NODE_ACCESS_ALLOW;
      }
    }

    if ($op == 'delete') {
      if (user_access('delete any ' . $type . ' content', $account) || (user_access('delete own ' . $type . ' content', $account) && ($account->uid == $node->uid))) {
        return NODE_ACCESS_ALLOW;
      }
    }
  }

  // Returning nothing from this function would have the same effect.
  return NODE_ACCESS_IGNORE;
}


/* vim: set filetype=php : */
?>
