<?php

function taxnav_menu() {

$path ='admin/taxnav/rebuild';
	$items[$path]=array();
		$items[$path]['title'] 			= 'Tax Nav Build';
		$items[$path]['desciption'] 		= 'Collect all node that are assigned the tax nav vocabulary and build their tree';
		$items[$path]['position'] 		= 'right';
		$items[$path]['weight'] 		= '-100';
		#$items[$path]['type'] 			=  MENU_CALLBACK;
		$items[$path]['page callback'] 		= 'build';
		$items[$path]['access arguments'] 	=  array('administer site configuration');
		$items[$path]['file'] 			= 'build.taxnav.inc';
		$items[$path]['file path'] 		=  drupal_get_path('module','taxnav');
	
	return $items;
};

function taxnav_taxonomy_term_delete($vocabulary){ _taxnav_taxonomy_change($vocabulary); }
function taxnav_taxonomy_term_insert($vocabulary){ _taxnav_taxonomy_change($vocabulary); }
function taxnav_taxonomy_term_update($vocabulary){ _taxnav_taxonomy_change($vocabulary); }

function _taxnav_taxonomy_change($vocabulary){
	if($vocabulary->vid== variable_get('taxnav_vocabulary')){
	include_once(drupal_get_path('module','taxnav').'/build.taxnav.inc');
	build();
	}
}


/* vim: set filetype=php : */
?>
