<?php
/**
 * @file
 * Lets user create pages in the about section of the site.
 *
 * Displays a link that lets authenticated users create about section pages.
 * All these pages are viewable by default to all the sites visitors.
 * Pages do not need to be approved. Default is to display the page.
 */

/**
 * Implementation of hook_menu().
 */


function about_menu() {

	$items['admin/config/about']=array(
		'title'			=> 'About Node configure',
		'desciption'		=> 'Configre options for the About page',
		'position'		=> 'right',
		'weight'		=> '-6',
		'page callback'		=> 'system_admin_menu_block_page',
		'access arguments'	=> array('administer site configuration'),
		'file'			=> 'system.admin.inc',
		'file path'		=> drupal_get_path('module','system'),
	);


	$items['admin/config/about/settings']=array(
		'title'			=> 'About page settings',
		'desciption'		=> 'Modify settings of the about pages',
		'page callback'		=> 'drupal_get_form',
		'page arguments'	=> array('about_admin_settings'),
		'access arguments'	=> array('administer site configuration'),
		'type'			=> MENU_NORMAL_ITEM,
		'file'			=> 'about.admin.inc',
	);

return $items;
};


/**
 * Implements hook_node_info() to provide info about type.
 */


function about_node_info(){
	return array(
		'about'=> array(
			'name' 		=> 'About Pages',
			'base' 		=> 'about',
			'description'	=> 'site About pages',
			'has_title'	=> 'TRUE',
			'title_label'	=> 'Page Name',
			'help'		=> 'Page will be displayed in menu under the FAQ page'
		)
	);
};


/* vim: set filetype=php : */
?>
