<?php

function workers_block_view_menu_workers_menu_alter(&$data,$block){

}

function nodes_of_type($type){
	$query = new EntityFieldQuery;
		$query->entityCondition('entity_type','node');
		$query->propertyCondition('type',$type);
			$results = $query->execute();
	
	$nodes = array();
		foreach($results as $unwrap){
			foreach($unwrap as $node){
			array_push($nodes,$node->nid);
			}
		}
xdebug_break();
	return node_load_multiple($nodes);
}


function workers_node_insert(){
	include_once(drupal_get_path('module','taxnav').'/build.taxnav.inc');
	build();
}

function workers_node_load($nodes,$types){

	
	if( sizeof($nodes)== 1 &&  $types[0]=='union'){	
		global $union_nid;
		$union_nid = current($nodes)->nid;
			dpm($union_nid,'Union nid set to ');
	}

	
}

function workers_query_node_default_alter($query){
	if(drupal_is_front_page()){
		dpm($query,'query');
		$query->condition('type','articles','=');
	}
}



?>
