<?php
/**
 * @file flickr_drive.module
 *
 * Displays a grid of photo thumbnail links from a Flickr feed.
 */

/**
 * Implementation of hook_init()
 */
function flickr_drive_init() {
	$flickr_path = drupal_get_path('module', 'flickr');
	require_once($flickr_path . '/flickr.api.inc');
}

/**
 * Implementation of hook_block_info()
 */
function flickr_drive_block_info() {
	$blocks['flickr_drive'] = array(
		'info' => t('Drive Box Flickr Thumbnails'),
		'status' => TRUE,
		'region' => 'footer',
		'weight' => 0,
		'visibility' => 1,
	);
	return $blocks;
}

/**
 * Implementation of hook_menu()
 */
function flickr_drive_menu() {
	$items['admin/config/flickr_drive'] = array(
		'title' => 'Flickr Drive Box',
		'description' => 'Displays the 2 most recent tagged photos in the site\'s Drive Box',
		'position' => 'right',
		'weight' => -5,
		'page callback' => 'system_admin_menu_block_page',
		'access arguments' => array('administer site configuration'),
		'file' => 'system.admin.inc',
		'file path' => drupal_get_path('module', 'system'),
	);

	$items['admin/config/flickr_drive/settings'] = array(
		'title' => 'Flickr Drive Box Settings',
		'description' => 'Flickr Drive Box Widget Settings',
		'page callback' => 'drupal_get_form',
		'page arguments' => array('flickr_drive_admin_settings'),
		'access arguments' => array('administer site configuration'),
		'type' => MENU_NORMAL_ITEM,
		'file' => 'flickr_drive.admin.inc',
	);

	return $items;
}

/**
 * Implementation of hook_theme()
 */
function flickr_drive_theme() {
	return array(
		'flickr_drive_thumbnail_list' => array(
			'variables' => array('items' => NULL, 'api_key' => NULL),
			'file' => 'flickr-drive.block.inc',
			'template' => 'flickr-drive-thumbnail-list',
		),
	);
}

/**
 * Implementation of hook_block_view()
 */
function flickr_drive_block_view($delta = '') {
	switch ($delta) {
		case 'flickr':
			$block['subject'] = t('Flickr Drive Box Block');
			$block['content'] = flickr_drive_block_contents($delta);
			return $block;
			break;
	}
}

// provides content for block_view function above
function flickr_drive_block_contents($delta) {
	switch ($delta) {
	case 'flickr':
		$api_key    = variable_get('flickr_drive_api_key', '6dccccbedab9f442055f9d2a25ab6428');
		$user_id    = variable_get('flickr_drive_user_nsid', '62751423@N00');
		$tag        = variable_get('flickr_drive_photo_tag', 'njldrive');
		$num_photos = variable_get('flickr_drive_num_photos', 2);
		$flickr     = new Flickr($api_key);
		$tagged     = $flickr->get_tagged_photos($tag, $num_photos);
		$photos     = array();

		$html = theme('flickr_drive_thumbnail_list', array('items' => $tagged['photo'], 'api_key' => $api_key));

		return array('#markup' => $html);
		break;
	}
}

// vim: set ft=php :
?>
